import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

const agents = [
    // --- Sales & Marketing ---
    {
        name: 'Sales Assistant Agent',
        slug: 'sales-assistant-agent',
        tagline: 'Turns complex quoting into a fast, intuitive guided experience.',
        description: 'Automates the sales quoting process by guiding reps through configuration, pricing, and proposal generation with AI-driven suggestions and real-time data from your ERP or CRM.',
        category: 'Alpha Dev',
        businessFunction: 'Sales',
        domain: 'CRM & Sales Automation',
        industry: 'Retail',
        status: 'LIVE',
        iconColor: '#4A5D4E',
        order: 1,
    },
    {
        name: 'Sales Qualification Agent',
        slug: 'sales-qualification-agent',
        tagline: 'Lead qualification and automated handover to sales.',
        description: 'Scores inbound leads based on firmographic and behavioural signals, routes qualified leads to the right sales rep, and generates AI-written outreach emails — all with no manual triage.',
        category: 'Alpha Dev',
        businessFunction: 'Sales',
        domain: 'CRM & Sales Automation',
        industry: 'B2B',
        status: 'LIVE',
        iconColor: '#3B5249',
        order: 2,
    },
    {
        name: 'Sales Preparation Agent',
        slug: 'sales-preparation-agent',
        tagline: 'Prepares sales meetings with unified customer data and insights.',
        description: 'Automatically pulls CRM history, recent news, LinkedIn activity, and deal context 30 minutes before a scheduled meeting — delivered as a concise briefing to the rep.',
        category: 'Alpha Dev',
        businessFunction: 'Sales',
        domain: 'CRM & Sales Automation',
        industry: 'B2B',
        status: 'LIVE',
        iconColor: '#2D4F41',
        order: 3,
    },
    {
        name: 'Next Best Action Agent',
        slug: 'next-best-action-agent',
        tagline: 'Proactive cross and upsell recommendations powered by customer data.',
        description: 'Analyses purchase history, product usage patterns, and customer lifecycle signals to recommend the highest-value next offer, delivered to the sales team in real time.',
        category: 'Alpha Dev',
        businessFunction: 'Sales',
        domain: 'AI & Analytics',
        industry: 'Retail',
        status: 'LIVE',
        iconColor: '#4A5D4E',
        order: 4,
    },
    {
        name: 'Conversational Intelligence Agent',
        slug: 'conversational-intelligence-agent',
        tagline: 'AI analysis of sales calls with insights and coaching support.',
        description: 'Transcribes and analyses every sales call to surface talk-time ratios, objection patterns, competitor mentions, and coaching opportunities — automatically synced back to the CRM.',
        category: 'Microsoft',
        businessFunction: 'Sales',
        domain: 'AI & Analytics',
        industry: 'B2B',
        status: 'LIVE',
        iconColor: '#0078D4',
        order: 5,
    },

    // --- Finance & Accounting ---
    {
        name: 'Invoice Matching Agent',
        slug: 'invoice-matching-agent',
        tagline: 'Automates invoice matching in Dynamics 365 F&O.',
        description: 'Uses AI to match incoming vendor invoices against purchase orders and goods receipts, flags discrepancies, and routes exceptions to the right approver — dramatically reducing manual AP effort.',
        category: 'Alpha Dev',
        businessFunction: 'Finance',
        domain: 'ERP & Finance',
        industry: 'Manufacturing',
        status: 'LIVE',
        iconColor: '#5C7A6E',
        order: 6,
    },
    {
        name: 'Reconciliation Agent',
        slug: 'reconciliation-agent',
        tagline: 'AI powered financial reconciliation and automated document matching.',
        description: 'Compares ledger entries against bank statements, ERP records, and third-party invoices to identify and resolve mismatches automatically, with a full audit trail for compliance.',
        category: 'Alpha Dev',
        businessFunction: 'Finance',
        domain: 'ERP & Finance',
        industry: 'Financial Services',
        status: 'LIVE',
        iconColor: '#4A5D4E',
        order: 7,
    },
    {
        name: 'Bank Statement Reconciliation Agent',
        slug: 'bank-statement-reconciliation-agent',
        tagline: 'Matches bank transactions with invoices to support reconciliation.',
        description: 'Ingests bank statement files in any format, extracts transaction data via OCR, and auto-matches against open invoices — delivering a reconciliation dashboard with one-click exception resolution.',
        category: 'Alpha Dev',
        businessFunction: 'Finance',
        domain: 'ERP & Finance',
        industry: 'Financial Services',
        status: 'LIVE',
        iconColor: '#3B5249',
        order: 8,
    },
    {
        name: 'Purchase Order Reconciliation Agent',
        slug: 'purchase-order-reconciliation-agent',
        tagline: 'Compares supplier confirmations with purchase orders and flags deviations.',
        description: 'Automatically ingests supplier order confirmations, maps line items to the original PO, identifies quantity or price mismatches, and notifies procurement teams for rapid resolution.',
        category: 'Alpha Dev',
        businessFunction: 'Finance',
        domain: 'ERP & Finance',
        industry: 'Manufacturing',
        status: 'LIVE',
        iconColor: '#2D4F41',
        order: 9,
    },
    {
        name: 'AP Responder Agent',
        slug: 'ap-responder-agent',
        tagline: 'Handles vendor payment enquiries and replies with invoice status.',
        description: 'Monitors the AP inbox, identifies payment status enquiries, looks up the relevant invoice in the ERP, and sends a structured, accurate reply — without human intervention.',
        category: 'Alpha Dev',
        businessFunction: 'Finance',
        domain: 'ERP & Finance',
        industry: 'Retail',
        status: 'LIVE',
        iconColor: '#4A5D4E',
        order: 10,
    },

    // --- Operations & Supply Chain ---
    {
        name: 'Order Intake Agent',
        slug: 'order-intake-agent',
        tagline: 'Automates email PDF orders into ERP sales orders.',
        description: 'Extracts order details from unstructured email PDFs using OCR and NLP, validates against the product catalogue, and creates clean sales orders in the ERP with zero manual data entry.',
        category: 'Alpha Dev',
        businessFunction: 'Operations',
        domain: 'Supply Chain & Logistics',
        industry: 'Manufacturing',
        status: 'LIVE',
        iconColor: '#5C7A6E',
        order: 11,
    },
    {
        name: 'Inbound Load Agent',
        slug: 'inbound-load-agent',
        tagline: 'Automates inbound load creation from vendor packing slips.',
        description: 'Reads incoming vendor packing slips, extracts item and quantity data, cross-references against open POs, and creates inbound load records in the WMS automatically.',
        category: 'Alpha Dev',
        businessFunction: 'Operations',
        domain: 'Supply Chain & Logistics',
        industry: 'Retail',
        status: 'LIVE',
        iconColor: '#4A5D4E',
        order: 12,
    },
    {
        name: 'Supply Chain Intelligence Agent',
        slug: 'supply-chain-intelligence-agent',
        tagline: 'Full visibility and operational manageability across your supply chain.',
        description: 'Our flagship supply chain agent connects vessel intake, OCR document processing, smart gantry dispatch, e-POD delivery, and SAP HANA integration into a single intelligent control tower.',
        category: 'Alpha Dev',
        businessFunction: 'Operations',
        domain: 'Supply Chain & Logistics',
        industry: 'Energy & Utilities',
        status: 'LIVE',
        iconColor: '#2D312E',
        order: 13,
    },

    // --- Customer Service ---
    {
        name: 'Customer Service Chatbot Agent',
        slug: 'customer-service-chatbot-agent',
        tagline: 'AI chatbot for scalable, high volume customer support.',
        description: 'Handles tier-1 customer enquiries 24/7 across chat, email, and messaging platforms. Uses RAG over your knowledge base to deliver accurate, on-brand answers, and escalates to human agents when needed.',
        category: 'Alpha Dev',
        businessFunction: 'Customer Service',
        domain: 'Customer Engagement',
        industry: 'Retail',
        status: 'LIVE',
        iconColor: '#4A5D4E',
        order: 14,
    },
    {
        name: 'Email Routing Agent',
        slug: 'email-routing-agent',
        tagline: 'Routes and prioritizes emails to the right service rep automatically.',
        description: 'Reads incoming customer emails, classifies intent and urgency using NLP, and routes each ticket to the correct team or rep — with priority scoring and SLA tracking built in.',
        category: 'Alpha Dev',
        businessFunction: 'Customer Service',
        domain: 'Customer Engagement',
        industry: 'B2B',
        status: 'LIVE',
        iconColor: '#3B5249',
        order: 15,
    },
    {
        name: 'Dynamic Email Routing Agent',
        slug: 'dynamic-email-routing-agent',
        tagline: 'Classifies and routes customer emails into Dynamics cases automatically.',
        description: 'Integrates directly with Dynamics 365 Customer Engagement to classify inbound emails, create or update cases, and assign them to the correct queue — eliminating manual triage entirely.',
        category: 'Alpha Dev',
        businessFunction: 'Customer Service',
        domain: 'Customer Engagement',
        industry: 'B2B',
        status: 'LIVE',
        iconColor: '#2D4F41',
        order: 16,
    },
    {
        name: 'Case Management Agent',
        slug: 'case-management-agent',
        tagline: 'Case creation and lifecycle management in Dynamics 365 Customer Engagement.',
        description: 'Automates the full case lifecycle — from creation and categorisation through to resolution and CSAT measurement — within Dynamics 365, with AI-suggested responses at every stage.',
        category: 'Microsoft',
        businessFunction: 'Customer Service',
        domain: 'Customer Engagement',
        industry: 'B2B',
        status: 'LIVE',
        iconColor: '#0078D4',
        order: 17,
    },
    {
        name: 'Move Care Agent',
        slug: 'move-care-agent',
        tagline: 'Automates end to end customer relocation processes.',
        description: 'Coordinates all touchpoints in a customer relocation journey — notification, scheduling, document collection, and status updates — through a single AI-orchestrated workflow.',
        category: 'Alpha Dev',
        businessFunction: 'Customer Service',
        domain: 'Customer Engagement',
        industry: 'Utilities',
        status: 'LIVE',
        iconColor: '#4A5D4E',
        order: 18,
    },

    // --- HR & Workforce ---
    {
        name: 'Time Entry Agent',
        slug: 'time-entry-agent',
        tagline: 'Automates time entry drafting, reminders and review workflows.',
        description: 'Monitors calendar events and project activity to suggest draft time entries, sends targeted reminders to employees who are behind, and flags timesheet anomalies for manager review.',
        category: 'Microsoft',
        businessFunction: 'HR',
        domain: 'Workforce Management',
        industry: 'Professional Services',
        status: 'LIVE',
        iconColor: '#0078D4',
        order: 19,
    },
    {
        name: 'Project & Time Agent',
        slug: 'project-and-time-agent',
        tagline: 'Streamlines time reporting and project insight in Business Central.',
        description: 'Integrates with Microsoft Business Central to automate time capture, surface project health metrics, and alert project managers to budget or timeline risks before they become problems.',
        category: 'Alpha Dev',
        businessFunction: 'HR',
        domain: 'Workforce Management',
        industry: 'Professional Services',
        status: 'LIVE',
        iconColor: '#4A5D4E',
        order: 20,
    },
    {
        name: 'CV Input Agent',
        slug: 'cv-input-agent',
        tagline: 'Aligns CVs and proposal content with RFP requirements.',
        description: 'Parses CVs and proposal documents, extracts relevant skills and experience, and maps them against RFP criteria — generating structured, compliant proposal sections at speed.',
        category: 'Alpha Dev',
        businessFunction: 'HR',
        domain: 'Document Processing',
        industry: 'Professional Services',
        status: 'LIVE',
        iconColor: '#3B5249',
        order: 21,
    },

    // --- IT & Compliance ---
    {
        name: 'Requirement Classification Agent',
        slug: 'requirement-classification-agent',
        tagline: 'Automates classification of IT procurement requirements.',
        description: 'Reads incoming IT procurement requests, classifies them by type and urgency using AI, and routes them to the appropriate approval workflow — reducing backlog and improving SLA adherence.',
        category: 'Alpha Dev',
        businessFunction: 'IT',
        domain: 'IT & Compliance',
        industry: 'Public Sector',
        status: 'LIVE',
        iconColor: '#4A5D4E',
        order: 22,
    },
    {
        name: 'Data Process Agreement Agent',
        slug: 'data-process-agreement-agent',
        tagline: 'Automates data processing agreement validation and compliance checks.',
        description: 'Reviews DPAs against regulatory requirements (GDPR, CCPA, etc.), flags non-compliant clauses, suggests remediation language, and tracks agreement status across your vendor portfolio.',
        category: 'Alpha Dev',
        businessFunction: 'IT',
        domain: 'IT & Compliance',
        industry: 'Financial Services',
        status: 'LIVE',
        iconColor: '#5C7A6E',
        order: 23,
    },
    {
        name: 'Regulatory Signal Agent',
        slug: 'regulatory-signal-agent',
        tagline: 'AI agent that tracks regulations and delivers impact summaries for legal teams.',
        description: 'Monitors regulatory feeds, government publications, and industry standards across multiple jurisdictions. Summarises changes, assesses business impact, and routes alerts to the relevant legal or compliance owner.',
        category: 'Alpha Dev',
        businessFunction: 'IT',
        domain: 'IT & Compliance',
        industry: 'Financial Services',
        status: 'LIVE',
        iconColor: '#4A5D4E',
        order: 24,
    },
    {
        name: 'Document Lifecycle Agent',
        slug: 'document-lifecycle-agent',
        tagline: 'Monitors document lifecycles and flags sensitive content.',
        description: 'Tracks document creation, review, approval, and expiry across SharePoint and connected systems. Automatically flags documents containing sensitive data and triggers retention or deletion workflows.',
        category: 'Alpha Dev',
        businessFunction: 'IT',
        domain: 'Document Processing',
        industry: 'Healthcare',
        status: 'LIVE',
        iconColor: '#2D4F41',
        order: 25,
    },

    // --- Knowledge & Search ---
    {
        name: 'Knowledge Discovery Agent',
        slug: 'knowledge-discovery-agent',
        tagline: 'Finds relevant knowledge and experts in Microsoft 365.',
        description: 'Uses semantic search across SharePoint, Teams, and email to surface the most relevant knowledge articles, documents, and internal subject matter experts for any given query.',
        category: 'Alpha Dev',
        businessFunction: 'Knowledge Management',
        domain: 'AI & Analytics',
        industry: 'Professional Services',
        status: 'LIVE',
        iconColor: '#4A5D4E',
        order: 26,
    },
    {
        name: 'Search in Cosmos DB Agent',
        slug: 'search-in-cosmos-db-agent',
        tagline: 'Natural language search for product data stored in Cosmos DB.',
        description: 'Enables business users to query product catalogues, inventory, and master data stored in Azure Cosmos DB using plain English — no SQL knowledge required.',
        category: 'Alpha Dev',
        businessFunction: 'Knowledge Management',
        domain: 'AI & Analytics',
        industry: 'Retail',
        status: 'LIVE',
        iconColor: '#3B5249',
        order: 27,
    },
    {
        name: 'Search in SQL DB Agent',
        slug: 'search-in-sql-db-agent',
        tagline: 'Search large product catalogues stored in SQL databases.',
        description: 'Translates natural language queries into optimised SQL, executes them against your database, and returns structured results with visualisations — making data accessible to non-technical users.',
        category: 'Alpha Dev',
        businessFunction: 'Knowledge Management',
        domain: 'AI & Analytics',
        industry: 'Retail',
        status: 'LIVE',
        iconColor: '#2D4F41',
        order: 28,
    },
    {
        name: 'Technical Guidelines Agent',
        slug: 'technical-guidelines-agent',
        tagline: 'Conversational access to technical requirements and guidelines.',
        description: 'Provides engineers and project teams with instant, conversational access to technical standards, design guidelines, and engineering specifications — reducing time spent searching documentation.',
        category: 'Alpha Dev',
        businessFunction: 'Knowledge Management',
        domain: 'Document Processing',
        industry: 'Manufacturing',
        status: 'LIVE',
        iconColor: '#4A5D4E',
        order: 29,
    },
    {
        name: 'Contract Information Search Agent',
        slug: 'contract-information-search-agent',
        tagline: 'Searches and extracts contract data from SharePoint.',
        description: 'Indexes contract repositories in SharePoint, extracts key clauses (renewal dates, obligations, SLAs), and answers natural language queries about contract terms — dramatically reducing legal research time.',
        category: 'Alpha Dev',
        businessFunction: 'Knowledge Management',
        domain: 'Document Processing',
        industry: 'Professional Services',
        status: 'LIVE',
        iconColor: '#5C7A6E',
        order: 30,
    },
    {
        name: 'Search and Reference in Large PDFs Agent',
        slug: 'search-and-reference-in-large-pdfs-agent',
        tagline: 'Search and reference information across large PDF documents.',
        description: 'Uses vector search and AI to find exact passages, tables, and figures within large PDF documents — returning precise page references and summaries without requiring users to read the entire document.',
        category: 'Alpha Dev',
        businessFunction: 'Knowledge Management',
        domain: 'Document Processing',
        industry: 'Financial Services',
        status: 'LIVE',
        iconColor: '#4A5D4E',
        order: 31,
    },

    // --- Product & Data Management ---
    {
        name: 'Product Search Agent',
        slug: 'product-search-agent',
        tagline: 'Modernises product search in Dynamics 365 F&O with smart lookup.',
        description: 'Replaces rigid catalogue search with AI-powered semantic product discovery in Dynamics 365 Finance & Operations — reducing search time and improving order accuracy.',
        category: 'Alpha Dev',
        businessFunction: 'Product Management',
        domain: 'ERP & Finance',
        industry: 'Manufacturing',
        status: 'LIVE',
        iconColor: '#4A5D4E',
        order: 32,
    },
    {
        name: 'Product Data Migration Agent',
        slug: 'product-data-migration-agent',
        tagline: 'The Product Data Migration Agent uses a Copilot Studio flow to extract product information from source systems.',
        description: 'Extracts product data from legacy PDFs and databases using OCR and AI parsing, structures it into a validated JSON format, and imports it into Dynamics 365 F&O — with full reconciliation reporting.',
        category: 'Alpha Dev',
        businessFunction: 'Product Management',
        domain: 'ERP & Finance',
        industry: 'Manufacturing',
        status: 'LIVE',
        iconColor: '#3B5249',
        order: 33,
    },
    {
        name: 'Product Specification Agent',
        slug: 'product-specification-agent',
        tagline: 'Extracts product specs to automate configuration and quoting.',
        description: 'Reads product specification sheets, extracts structured attributes, and populates product configurators and CPQ tools automatically — accelerating quote turnaround and reducing configuration errors.',
        category: 'Alpha Dev',
        businessFunction: 'Product Management',
        domain: 'Document Processing',
        industry: 'Manufacturing',
        status: 'LIVE',
        iconColor: '#2D4F41',
        order: 34,
    },
    {
        name: 'Product Master Data Agent',
        slug: 'product-master-data-agent',
        tagline: 'Automates product master data with smart suggestions and anomaly alerts.',
        description: 'Monitors product master data for completeness, consistency, and anomalies. Suggests enrichment values using AI, flags duplicate records, and enforces data governance rules across ERP and PIM systems.',
        category: 'Alpha Dev',
        businessFunction: 'Product Management',
        domain: 'ERP & Finance',
        industry: 'Retail',
        status: 'LIVE',
        iconColor: '#4A5D4E',
        order: 35,
    },
    {
        name: 'Supplier Communication Agent',
        slug: 'supplier-communication-agent',
        tagline: 'Automates supplier emails and purchase order updates in ERP.',
        description: 'Reads supplier emails, extracts delivery updates, acknowledgements, and exceptions, and posts structured updates back to the ERP — keeping procurement teams informed without inbox overload.',
        category: 'Microsoft',
        businessFunction: 'Operations',
        domain: 'Supply Chain & Logistics',
        industry: 'Manufacturing',
        status: 'LIVE',
        iconColor: '#0078D4',
        order: 36,
    },

    // --- Specialised ---
    {
        name: 'Qlik Documentation Agent',
        slug: 'qlik-documentation-agent',
        tagline: 'Generates structured Qlik documentation with field level lineage.',
        description: 'Automatically documents Qlik Sense and QlikView applications — extracting field lineage, expression logic, and data model details — into structured, always-up-to-date reference documentation.',
        category: 'Alpha Dev',
        businessFunction: 'IT',
        domain: 'AI & Analytics',
        industry: 'Financial Services',
        status: 'LIVE',
        iconColor: '#5C7A6E',
        order: 37,
    },
    {
        name: 'Migration Mapping Agent',
        slug: 'migration-mapping-agent',
        tagline: 'Automates complex data migration field mappings with AI.',
        description: 'Analyses source and target data schemas, uses AI to suggest field mappings, resolves naming and type mismatches, and outputs a validated transformation specification ready for the migration team.',
        category: 'Alpha Dev',
        businessFunction: 'IT',
        domain: 'ERP & Finance',
        industry: 'Manufacturing',
        status: 'LIVE',
        iconColor: '#4A5D4E',
        order: 38,
    },
    {
        name: 'Conversation Analysis Agent',
        slug: 'conversation-analysis-agent',
        tagline: 'Analyses service call transcripts to score quality and compliance.',
        description: 'Transcribes customer service calls, scores them against predefined quality frameworks and compliance requirements, and delivers agent-level scorecards and trend reports to QA managers.',
        category: 'Alpha Dev',
        businessFunction: 'Customer Service',
        domain: 'AI & Analytics',
        industry: 'Financial Services',
        status: 'LIVE',
        iconColor: '#3B5249',
        order: 39,
    },
    {
        name: 'Document to Sales Order Agent',
        slug: 'document-to-sales-order-agent',
        tagline: 'Converts documents into validated Sales Orders in Dynamics 365.',
        description: 'Ingests order documents in any format (PDF, EDI, email), extracts line items and customer details using AI, validates against the product catalogue and customer master, and creates sales orders in Dynamics 365.',
        category: 'Alpha Dev',
        businessFunction: 'Sales',
        domain: 'ERP & Finance',
        industry: 'Manufacturing',
        status: 'LIVE',
        iconColor: '#2D4F41',
        order: 40,
    },
    {
        name: 'Conversion Agent',
        slug: 'conversion-agent',
        tagline: 'Converts legacy documents and metadata to modern formats.',
        description: 'Transforms legacy document formats, metadata schemas, and data structures into modern, standards-compliant formats — enabling seamless migration and integration without data loss.',
        category: 'Alpha Dev',
        businessFunction: 'IT',
        domain: 'Document Processing',
        industry: 'Public Sector',
        status: 'LIVE',
        iconColor: '#4A5D4E',
        order: 41,
    },
    {
        name: 'Emission AI Agent',
        slug: 'emission-ai-agent',
        tagline: 'Maps purchase orders to emission factors for Scope 3 reporting.',
        description: 'Analyses purchase order data, maps spend categories to relevant emission factors from DEFRA, EPA, and GHG Protocol sources, and generates Scope 3 Category 1 emissions reports ready for ESG disclosure.',
        category: 'Alpha Dev',
        businessFunction: 'Sustainability',
        domain: 'IT & Compliance',
        industry: 'Energy & Utilities',
        status: 'LIVE',
        iconColor: '#2D7A4F',
        order: 42,
    },
    {
        name: 'ERP Migration Agent',
        slug: 'erp-migration-agent',
        tagline: 'Intelligent data migration from legacy ERP to modern platforms.',
        description: 'Orchestrates end-to-end ERP migrations using AI-powered field mapping, data cleansing, and validation. Supports migrations to Dynamics 365, SAP S/4HANA, and Oracle Fusion with full reconciliation reporting.',
        category: 'Alpha Dev',
        businessFunction: 'IT',
        domain: 'ERP & Finance',
        industry: 'Manufacturing',
        status: 'LIVE',
        iconColor: '#4A5D4E',
        order: 43,
    },
    {
        name: 'CV Safety Monitoring Agent',
        slug: 'cv-safety-monitoring-agent',
        tagline: 'Real-time AI-powered safety monitoring for industrial environments.',
        description: 'Leverages computer vision to detect PPE violations, SOP breaches, exclusion zone intrusions, and unsafe behaviours in real time — delivering instant alerts and a compliance dashboard for safety managers.',
        category: 'Alpha Dev',
        businessFunction: 'Operations',
        domain: 'AI & Analytics',
        industry: 'Manufacturing',
        status: 'LIVE',
        iconColor: '#7A3B3B',
        order: 44,
    },
];

async function main() {
    console.log('🤖 Seeding AI Agents...');

    for (const agent of agents) {
        await (prisma as any).aIAgent.upsert({
            where: { slug: agent.slug },
            update: agent,
            create: agent,
        });
        console.log(`  ✓ ${agent.name}`);
    }

    console.log(`\n✅ Done — ${agents.length} AI agents seeded.`);
}

main()
    .catch((e) => {
        console.error(e);
        process.exit(1);
    })
    .finally(async () => {
        await prisma.$disconnect();
    });
